#!/usr/bin/env -S guile -s
!#

(use-modules (ice-9 match))

(unless (= 2 (length (command-line))) (display "this script takes one argument") (newline) (primitive-exit))

(match (cadr (command-line))
  ("home" (system* "guix" "time-machine" "-C" "channels.lock" "--" "home" "reconfigure" "-L." "atlas/home/home.scm"))
  ("system" (system* "sudo" "guix" "time-machine" "-C" "channels.lock" "--" "system" "reconfigure" "atlas/system/system.scm" "-L."))
  (_ (display "enter either `home` or `system`") (newline)))

;; Local Variables:
;; mode: scheme
;; End:
