((:title "Marast"
         :url "https://marast.fit.cvut.cz"
         :tags ("ctu"))
 (:title "Kos"
         :url "https://kos.cvut.cz"
         :tags ("ctu"))
 (:title "Courses"
         :url "https://courses.fit.cvut.cz"
         :tags ("ctu"))
 (:title "Syncthing"
         :url "http://localhost:8384"))
