icons = "awesome"
scrolling = "reverse"

[theme]
name = "gruvbox-dark"
[theme.overrides]
good_bg = "#123456"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/home/michal-atlas/Games"
alias = "Games"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

#[[block]]
#block= "keyboard_layout"
#driver="setxkbmap"
#format="{layout} {variant}"

[[block]]
block = "networkmanager"
on_click = "kitty -e nmtui"

[[block]]
block = "toggle"

text = "PIC"
command_state = "ps aux | grep 'picom$'"
interval = 5 
command_off = "pkill picom"
command_on = "tmux new-session -d picom"

[[block]]
interval=10
block = "nvidia_gpu"

#[[block]]
#block = "pacman"
#interval = 6000
#format = "{pacman}"
#format_up_to_date = ""
#critical_updates_regex = "(linux |linux-lts|linux-zen)"

#[[block]]
#block = "memory"
#display_type = "memory"
#format_mem = "{Mup}%"
#format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"
on_click = "kitty -e rsmixer"

[[block]]
block = "custom"
command = "decimal-clock.rs"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
#format = "%Y-%m-%dT%H:%M"
