(define-module (home packages)
  #:use-module (gnu home services)
  #:use-module (atlas utils services)
  #:use-module (gnu)
  #:use-module (ice-9 match)
  #:use-module (atlas packages shen)
  #:use-module (nongnu packages mozilla)
  #:use-module (nongnu packages gog)
  #:use-module (nongnu packages game-client)
  #:use-module (sops packages sops)
  #:use-module (games packages the-ur-quan-masters)
  #:use-module (games packages minecraft)
  #:use-module (guix packages)
  #:use-module (guix cpu)
  #:export (packages))

(use-package-modules
 acl
 admin
 base
 bittorrent
 certs
 chez
 code
 commencement
 compression
 containers
 cups
 curl
 databases
 dictionaries
 disk
 dns
 elf
 emacs
 guile-xyz
 emacs-xyz
 file
 fonts
 fontutils
 freedesktop
 game-development
 games
 gdb
 ghostscript
 gimp
 gnome
 gnome-xyz
 gnunet
 gnuzilla
 graphviz
 haskell
 haskell-apps
 haskell-xyz
 image
 image-viewers
 imagemagick
 inkscape
 irc
 kde
 kde-frameworks
 linux
 lisp
 lisp-xyz
 lsof
 mail
 maths
 messaging
 music
 networking
 node
 ocaml
 package-management
 parallel
 password-utils
 perl
 pkg-config
 prolog
 pulseaudio
 python
 python-xyz
 rdesktop
 readline
 rsync
 rust-apps
 samba
 screen
 shells
 shellutils
 skribilo
 ssh
 sync
 telegram
 terminals
 tex
 texinfo
 texlive
 text-editors
 tls
 version-control
 video
 vim
 virtualization
 w3m
 web
 web-browsers
 wine
 wm
 xdisorg)

(define packages
  (+s home-profile system-packages
      (append
       (list
        `(,git "send-email")
        `(,isc-bind "utils")
        acl
        adwaita-icon-theme
        bat
        bemenu
        breeze-icons
        btrfs-progs
        carp
        chez-scheme
        compsize
        curl
        direnv
        ecl
        ed
        fasd
        feh
        ffmpeg
        fheroes2
        file
        firefox
        flatpak
        foot
        fzf
        gcc-toolchain
        gdb
        ghc
        gimp
        git
        git-lfs
        gmnisrv
        gnu-make
        gnunet
        gnome-shell-extension-appindicator
        gnome-shell-extension-blur-my-shell
        gnome-shell-extension-burn-my-windows
        gnome-shell-extension-clipboard-indicator
        gnome-shell-extension-customize-ibus
        gnome-shell-extension-dash-to-dock
        gnome-shell-extension-dash-to-panel
        gnome-shell-extension-gsconnect
        gnome-shell-extension-hide-app-icon
        gnome-shell-extension-jiggle
        gnome-shell-extension-just-perfection
        gnome-shell-extension-night-theme-switcher
        gnome-shell-extension-noannoyance
        gnome-shell-extension-paperwm
        gnome-shell-extension-radio
        gnome-shell-extension-sound-output-device-chooser
        gnome-shell-extension-topicons-redux
        gnome-shell-extension-transparent-window
        gnome-shell-extension-unite-shell
        gnome-shell-extension-vertical-overview
        gnome-shell-extension-vitals
        gparted
        graphviz
        grim
        guix-icons
        gzdoom
        heroic
        hicolor-icon-theme
        htop
        hut
        icedove/wayland
        imagemagick
        indent
        inkscape
        inotify-tools
        irssi
        guile-ares-rs
        jq
        keepassxc
        kineto
        krita
        lagrange
        lgogdownloader
        lsof
        lvm2
        mailutils
        maxima
        mosh
        nautilus
        ndisc6
        netcat
        nheko
        nix
        node
        nyxt
        okular
        openmw
        openssl
        oxygen-icons
        p7zip
        pagekite
        pandoc
        parallel
        pass-otp
        password-store
        patchelf
        pavucontrol
        perl
        pkg-config
        playerctl
        podman
        pre-commit
        prismlauncher
        python
        python-ipython
        recutils
        rlwrap
        rsync
        sbcl
        sbcl-alexandria
        sbcl-cffi
        sbcl-cl-yacc
        sbcl-clingon
        sbcl-coalton
        sbcl-iterate
        sbcl-linedit
        sbcl-log4cl
        sbcl-lparallel
        sbcl-mcclim
        sbcl-parenscript
        sbcl-s-xml
        sbcl-screamer
        sbcl-serapeum
        sbcl-series
        sbcl-tailrec
        sbcl-tar
        sbcl-terminal-keypress
        sbcl-terminal-size
        sbcl-terminfo
        sbcl-trees
        sbcl-trial
        sbcl-unix-opts
        screen
        shellcheck
        shen-c
        shen-scheme
        shotwell
        skribilo
        slurp
        sops
        steam
        supertux
        supertuxkart
        swi-prolog
        tealdeer
        telegram-desktop
        texinfo
        translate-shell
        transmission-remote-gtk
        tree
        unison
        unzip
        uqm
        vcmi
        virt-manager
        vlc
        w3m
        wdisplays
        wine64
        wireshark
        wl-clipboard
        wtype
        xdg-desktop-portal-wlr
        xdg-utils
        xdot
        xonotic
        xxd
        zoxide
        yt-dlp))))
