# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  networking.hostName = "dagon";

  nix.buildMachines = [{
    hostName = "hydra";
    system = "x86_64-linux";
    # if the builder supports building for multiple architectures, 
    # replace the previous line by, e.g.,
    # systems = ["x86_64-linux" "aarch64-linux"];
    maxJobs = 6;
    speedFactor = 2;
    supportedFeatures = [ "nixos-test" "benchmark" "big-parallel" "kvm" ];
    mandatoryFeatures = [ ];
    sshUser = "michal_atlas";
    sshKey = "/home/michal_atlas/.ssh/id_rsa";
    publicHostKey = "c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUFDLytHQ0F1RFNxMmt5U3c0K3lCMVUzVjk1Z0YrdjdNOUE1cTE4YXQrWVogcm9vdEBuaXhvcwo=";
  }];
  nix.distributedBuilds = true;
  # optional, useful when the builder has a faster internet connection than yours
  nix.extraOptions = "	builders-use-substitutes = true\n";

}
