# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    ../templates/desktop.nix
    ../templates/morrowind-server.nix
    ../templates/i2p.nix
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ahci" "usb_storage" "uas" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" "amdgpu" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "ntfs" ];

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/C9ED-A99E";
    fsType = "vfat";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/1a20f616-635b-46af-bf07-ff09cf461504"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;

  networking.hostName = "hydra";

  services.btrfs.autoScrub.enable = true;
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/e2f2bd08-7962-4e9d-a22a-c66972b7b1e3";
      options = [ "subvol=@nix" ];
      fsType = "btrfs";
    };
    "/home" = {
      device = "/dev/disk/by-uuid/e2f2bd08-7962-4e9d-a22a-c66972b7b1e3";
      options = [ "subvol=@home" ];
      fsType = "btrfs";
    };
    "/tes3mp" = {
      device = "/dev/disk/by-uuid/e2f2bd08-7962-4e9d-a22a-c66972b7b1e3";
      options = [ "subvol=@tes3mp" ];
      fsType = "btrfs";
    };
    "/GAMES" = {
      device = "/dev/disk/by-uuid/09bd533f-e008-4ed8-bc30-eeae89429821";
      options = [ "subvol=@games" ];
      fsType = "btrfs";
    };
    "/DOWNLOADS" = {
      device = "/dev/disk/by-uuid/e24e064b-5f09-47b8-be7b-3ac41aff85e7";
      options = [ "subvol=@downloads" ];
      fsType = "btrfs";
    };
  };
}
