# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  networking.hostName = "hydra";
  nix.settings.trusted-users = [ "michal_atlas" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];

  fileSystems."/GAMES" = {
    device = "/dev/disk/by-label/Games-Z";
    fsType = "ntfs-3g";
    options = [
      "uid=michal_atlas"
      "gid=users"
    ];
  };
  fileSystems."/home" = {
    fsType = "btrfs";
    device = "/dev/VG/guix";
    options = [
      "subvol=@home"
    ];
  };
}
