{
  pkgs,
  ...
}:
{
  imports = [
    ./scripts.nix
  ];
  home.packages = with pkgs; [
    (hiPrio gcc)
    (python311.withPackages (
      ps: with ps; [
        # keep-sorted start
        dbus-python
        ipython
        matplotlib
        numpy
        pygments
        pytorch
        scipy
        transformers
        # keep-sorted end
      ]
    ))
    (sbcl.withPackages (
      ps: with ps; [
        # keep-sorted start
        alexandria
        cffi
        cl-autowrap
        cl-conspack
        cl-css
        cl-fuse-meta-fs
        cl-strings
        cl-who
        clingon
        clsql
        coalton
        coleslaw
        collectors
        dbd-sqlite3
        eclector
        generators
        harmony
        hunchentoot
        iterate
        linedit
        log4cl
        lparallel
        mcclim
        mcclim-layouts
        mito
        optima
        parenscript
        parser-combinators
        s-xml
        screamer
        serapeum
        series
        str
        sycamore
        tailrec
        tar
        terminfo
        trees
        unix-opts
        yacc
        # keep-sorted end
      ]
    ))
    # keep-sorted start
    acl
    alejandra
    ani-cli
    apostrophe
    ascii-draw
    audacity
    bat
    blender
    bluetuith
    boxes
    btrfs-progs
    cachix
    calibre
    caprine-bin
    ccls
    chez
    cht-sh
    cifs-utils
    citations
    clang
    clang-tools
    cmake
    compsize
    cryptsetup
    diffoscope
    dig
    direnv
    dust
    ecl
    ed
    element-desktop
    feh
    ffmpeg
    file
    foliate
    fzf
    gdb
    gh
    ghc
    gimp
    git
    gmic
    gnome-decoder
    gnome-feeds
    gnome-frog
    gnome-podcasts
    gnome-secrets
    gnugo
    gnumake
    gnupg
    gparted
    gprolog
    graphs
    graphviz
    guile
    gzdoom
    halftone
    haskell-language-server
    heroic
    hieroglyphic
    hut
    hyperfine
    imagemagick
    indent
    inkscape
    inotify-tools
    ipfs
    ipscan
    isync
    jetbrains.clion
    jetbrains.datagrip
    jetbrains.goland
    jetbrains.idea-ultimate
    jetbrains.pycharm-professional
    jetbrains.rust-rover
    jetbrains.webstorm
    jq
    kobodeluxe
    komikku
    krita
    lagrange
    lazygit
    libnotify
    libreoffice
    libtool
    linuxPackages.perf
    lorem
    lsof
    manix
    maxima
    meld
    mosh
    mousai
    mpv
    nethogs
    nil
    nix
    nix-diff
    nix-melt
    nix-output-monitor
    nix-prefetch
    nix-tree
    nixfmt-rfc-style
    nmap
    nodejs
    nurl
    nvd
    okular
    onedrive
    openai-whisper
    openmw
    openra
    openssl
    p7zip
    pandoc
    patchelf
    pavucontrol
    peertube.cli
    pkg-config
    playerctl
    polari
    prismlauncher
    protonmail-desktop
    protonvpn-gui
    pulsemixer
    qbittorrent
    qpwgraph
    racket
    rclone
    rlwrap
    rsync
    rustup
    screen
    snapshot
    sshfs
    steam-run
    superTux
    superTuxKart
    taisei
    tangram
    teams-for-linux
    telegram-desktop
    texlive.combined.scheme-full
    textpieces
    tldr
    tree
    unison-ucm
    unzip
    uqm
    usbutils
    valgrind
    vcmi
    video-trimmer
    virt-manager
    vlc
    vpsfree-client
    wdisplays
    webcord
    wesnoth
    wget
    whatsapp-for-linux
    wike
    wineWowPackages.full
    winetricks
    wireshark
    wl-clipboard
    wl-mirror
    xdg-utils
    xdot
    xmlstarlet
    xonotic
    xournalpp
    xxd
    yt-dlp
    # keep-sorted end
  ];
}
