#! /bin/sh
# -*- mode: scheme; coding: utf-8 -*-
exec guix repl -- "$0" "$@"
!#

(when (not (= 0 (getuid)))
  (format #t "Please run as root.~%")
  (exit))

(add-to-load-path (getcwd))
(use-modules
 (guix scripts time-machine)
 (scripts config))

(apply guix-time-machine
       `("-C" ,channel-lock-file ,@(cdr (command-line))
	 "--" "system" "reconfigure" "-L"
	 ,dotfile-dir
	 ,system-config
	 ,@(cdr (command-line))))

;; Local Variables:
;; mode: scheme
;; End:
