name: Bump flake.lock
on:
  schedule:
    - cron: "0 0 * * 6"
  workflow_dispatch:
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: commitizen-tools/commitizen-action@master
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
  flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@v16
      - uses: DeterminateSystems/update-flake-lock@v24
